<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);SKEXP0010</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.8" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.18.1" />
    <PackageReference Include="Microsoft.SemanticKernel" Version="1.77.0" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.OpenAI" Version="1.77.0" />
    <PackageReference Include="PdfPig" Version="0.1.10" />
    <PackageReference Include="Qdrant.Client" Version="1.18.1" />
    <PackageReference Include="StackExchange.Redis" Version="2.7.27" />
    <PackageReference Include="Volo.Abp.EntityFrameworkCore" Version="8.1.5" />
    <PackageReference Include="Volo.Abp.EntityFrameworkCore.SqlServer" Version="8.1.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WeiDin.Core\WeiDin.Core.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <Folder Include="Modules\" />
  </ItemGroup>

</Project>
